name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Har kuni yarim tunda ishga tushadi
  workflow_dispatch:  # Qo'lda ishga tushirishga ruxsat

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload to GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/snake.svg
